/*
 * generated by Xtext
 */
package ru.spbau.luchikhin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GraphUiModule extends ru.spbau.luchikhin.ui.AbstractGraphUiModule {
	public GraphUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
