package Stopwatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Appearance_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Appearance_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Stopwatch.structure.Appearance";
  }
}
