package Stopwatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Timeline_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Timeline_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Stopwatch.structure.Timeline";
  }
}
