package tracer.runtime;

/*Generated by MPS */


public class TracerContext {
  public boolean time;


  public TracerContext(String time) {
    this.time = Boolean.parseBoolean(time);
  }
}
