package tracer.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {


  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new CallingTracer_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Log_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new LogFormat_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ModificationsTracer_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new ReferencesTracer_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }



  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"tracer.structure.CallingTracer", "tracer.structure.Log", "tracer.structure.LogFormat", "tracer.structure.ModificationsTracer", "tracer.structure.ReferencesTracer"};
}
