/*
 * generated by Xtext
 */
package ru.spbau.luchikhin.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ru.spbau.luchikhin.ui.internal.GraphActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraphExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GraphActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GraphActivator.getInstance().getInjector(GraphActivator.RU_SPBAU_LUCHIKHIN_GRAPH);
	}
	
}
