/**
 * generated by Xtext
 */
package ru.spbau.luchikhin.validation;

import ru.spbau.luchikhin.validation.AbstractGraphValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GraphValidator extends AbstractGraphValidator {
}
