package Stopwatch.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.MPSFonts;
import jetbrains.mps.nodeEditor.BlockCells;
import jetbrains.mps.nodeEditor.cells.EditorCell_Indent;
import jetbrains.mps.lang.editor.cellProviders.RefNodeCellProvider;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import jetbrains.mps.smodel.action.NodeFactoryManager;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import jetbrains.mps.nodeEditor.cellMenu.DefaultReferenceSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class Stopwatch_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_gq055b_a(editorContext, node);
  }

  private EditorCell createCollection_gq055b_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_gq055b_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createCollection_gq055b_a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_gq055b_a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_gq055b_a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_gq055b_a0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_b0a(editorContext, node));
    if (renderingCondition_gq055b_a2a0(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_gq055b_c0a(editorContext, node));
    }
    return editorCell;
  }

  private EditorCell createCollection_gq055b_a0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_gq055b_a0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_gq055b_a0a0(editorContext, node));
    if (renderingCondition_gq055b_a1a0a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_gq055b_b0a0(editorContext, node));
    }
    return editorCell;
  }

  private EditorCell createCollection_gq055b_a0a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_gq055b_a0a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_gq055b_a0a0a(editorContext, node));
    editorCell.addEditorCell(this.createProperty_gq055b_b0a0a(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_gq055b_a0a0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "stopwatch");
    editorCell.setCellId("Constant_gq055b_a0a0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_gq055b_b0a0a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_gq055b_b0a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_gq055b_b0a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, true);
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static boolean renderingCondition_gq055b_a1a0a(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }

  private EditorCell createCollection_gq055b_b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_gq055b_b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_gq055b_a1a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_b1a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createIndentCell_gq055b_a1a0(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }

  private EditorCell createCollection_gq055b_b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_gq055b_b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_gq055b_a1b0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_b1b0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_c1b0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_d1b0a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_gq055b_e1b0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_f1b0a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_gq055b_g1b0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_h1b0a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_gq055b_i1b0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_j1b0a(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_gq055b_a1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_gq055b_a1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_gq055b_a0b1a0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_gq055b_b0b1a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_gq055b_a0b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Purpose:");
    editorCell.setCellId("Constant_gq055b_a0b1a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_gq055b_b0b1a0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("purpose");
    provider.setNoTargetText("<no purpose>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_purpose");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createCollection_gq055b_b1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_gq055b_b1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_gq055b_a1b1a0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_gq055b_b1b1a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_gq055b_a1b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Usage:");
    editorCell.setCellId("Constant_gq055b_a1b1a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_gq055b_b1b1a0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("usage");
    provider.setNoTargetText("<no usage>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_usage");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createCollection_gq055b_c1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_gq055b_c1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_gq055b_a2b1a0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_gq055b_b2b1a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_gq055b_a2b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Principle:");
    editorCell.setCellId("Constant_gq055b_a2b1a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_gq055b_b2b1a0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("principle");
    provider.setNoTargetText("<no principle>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_principle");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createCollection_gq055b_d1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_gq055b_d1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_gq055b_a3b1a0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_gq055b_b3b1a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_gq055b_a3b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Maximum time:");
    editorCell.setCellId("Constant_gq055b_a3b1a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createRefNode_gq055b_b3b1a0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefNodeCellProvider(node, editorContext);
    provider.setRole("maximumTime");
    provider.setNoTargetText("<no maximumTime>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    if (editorCell.getRole() == null) {
      editorCell.setRole("maximumTime");
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_gq055b_e1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_gq055b_e1b0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createCollection_gq055b_f1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_gq055b_f1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_gq055b_a5b1a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_b5b1a0(editorContext, node));
    if (renderingCondition_gq055b_a2f1b0a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_gq055b_c5b1a0(editorContext, node));
    }
    return editorCell;
  }

  private EditorCell createCollection_gq055b_a5b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_gq055b_a5b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_gq055b_a0f1b0a(editorContext, node));
    if (renderingCondition_gq055b_a1a5b1a0(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_gq055b_b0f1b0a(editorContext, node));
    }
    return editorCell;
  }

  private EditorCell createConstant_gq055b_a0f1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Appearance");
    editorCell.setCellId("Constant_gq055b_a0f1b0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_gq055b_b0f1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_gq055b_b0f1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, true);
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static boolean renderingCondition_gq055b_a1a5b1a0(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }

  private EditorCell createCollection_gq055b_b5b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_gq055b_b5b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_gq055b_a1f1b0a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_gq055b_b1f1b0a(editorContext, node));
    return editorCell;
  }

  private EditorCell createIndentCell_gq055b_a1f1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }

  private EditorCell createRefNode_gq055b_b1f1b0a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefNodeCellProvider(node, editorContext);
    provider.setRole("appearance");
    provider.setNoTargetText("<no appearance>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    if (editorCell.getRole() == null) {
      editorCell.setRole("appearance");
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_gq055b_c5b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_gq055b_c5b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, true);
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static boolean renderingCondition_gq055b_a2f1b0a(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }

  private EditorCell createConstant_gq055b_g1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_gq055b_g1b0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createCollection_gq055b_h1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_gq055b_h1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_gq055b_a7b1a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_b7b1a0(editorContext, node));
    if (renderingCondition_gq055b_a2h1b0a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_gq055b_c7b1a0(editorContext, node));
    }
    return editorCell;
  }

  private EditorCell createCollection_gq055b_a7b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_gq055b_a7b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_gq055b_a0h1b0a(editorContext, node));
    if (renderingCondition_gq055b_a1a7b1a0(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_gq055b_b0h1b0a(editorContext, node));
    }
    return editorCell;
  }

  private EditorCell createConstant_gq055b_a0h1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Timelines");
    editorCell.setCellId("Constant_gq055b_a0h1b0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_gq055b_b0h1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_gq055b_b0h1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, true);
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static boolean renderingCondition_gq055b_a1a7b1a0(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }

  private EditorCell createCollection_gq055b_b7b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_gq055b_b7b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_gq055b_a1h1b0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_b1h1b0a(editorContext, node));
    return editorCell;
  }

  private EditorCell createIndentCell_gq055b_a1h1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }

  private EditorCell createCollection_gq055b_b1h1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_gq055b_b1h1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createRefNodeList_gq055b_a1b7b1a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createRefNodeList_gq055b_a1b7b1a0(EditorContext editorContext, SNode node) {
    AbstractCellListHandler handler = new Stopwatch_Editor.timelinesListHandler_gq055b_a1b7b1a0(node, "timelines", editorContext);
    EditorCell_Collection editorCell = handler.createCells(editorContext, new CellLayout_Vertical(), false);
    editorCell.setCellId("refNodeList_timelines");
    editorCell.setRole(handler.getElementRole());
    return editorCell;
  }

  private static class timelinesListHandler_gq055b_a1b7b1a0 extends RefNodeListHandler {
    public timelinesListHandler_gq055b_a1b7b1a0(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
    }

    public SNode createNodeToInsert(EditorContext editorContext) {
      SNode listOwner = super.getOwner();
      return NodeFactoryManager.createNode(listOwner, editorContext, super.getElementRole());
    }

    public EditorCell createNodeCell(EditorContext editorContext, SNode elementNode) {
      EditorCell elementCell = super.createNodeCell(editorContext, elementNode);
      this.installElementCellActions(this.getOwner(), elementNode, elementCell, editorContext);
      return elementCell;
    }

    public EditorCell createEmptyCell(EditorContext editorContext) {
      EditorCell emptyCell = null;
      emptyCell = super.createEmptyCell(editorContext);
      this.installElementCellActions(super.getOwner(), null, emptyCell, editorContext);
      return emptyCell;
    }

    public void installElementCellActions(SNode listOwner, SNode elementNode, EditorCell elementCell, EditorContext editorContext) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        if (elementNode != null) {
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode));
          elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultReferenceSubstituteInfo) {
          elementCell.setSubstituteInfo(new DefaultChildSubstituteInfo(listOwner, elementNode, super.getLinkDeclaration(), editorContext));
        }
      }
    }
  }

  private EditorCell createConstant_gq055b_c7b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_gq055b_c7b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, true);
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static boolean renderingCondition_gq055b_a2h1b0a(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }

  private EditorCell createConstant_gq055b_i1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_gq055b_i1b0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createCollection_gq055b_j1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_gq055b_j1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_gq055b_a9b1a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_b9b1a0(editorContext, node));
    if (renderingCondition_gq055b_a2j1b0a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_gq055b_c9b1a0(editorContext, node));
    }
    return editorCell;
  }

  private EditorCell createCollection_gq055b_a9b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_gq055b_a9b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_gq055b_a0j1b0a(editorContext, node));
    if (renderingCondition_gq055b_a1a9b1a0(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_gq055b_b0j1b0a(editorContext, node));
    }
    return editorCell;
  }

  private EditorCell createConstant_gq055b_a0j1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Buttons");
    editorCell.setCellId("Constant_gq055b_a0j1b0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_gq055b_b0j1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_gq055b_b0j1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, true);
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static boolean renderingCondition_gq055b_a1a9b1a0(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }

  private EditorCell createCollection_gq055b_b9b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_gq055b_b9b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_gq055b_a1j1b0a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_gq055b_b1j1b0a(editorContext, node));
    return editorCell;
  }

  private EditorCell createIndentCell_gq055b_a1j1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }

  private EditorCell createCollection_gq055b_b1j1b0a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_gq055b_b1j1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createRefNodeList_gq055b_a1b9b1a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createRefNodeList_gq055b_a1b9b1a0(EditorContext editorContext, SNode node) {
    AbstractCellListHandler handler = new Stopwatch_Editor.buttonsListHandler_gq055b_a1b9b1a0(node, "buttons", editorContext);
    EditorCell_Collection editorCell = handler.createCells(editorContext, new CellLayout_Vertical(), false);
    editorCell.setCellId("refNodeList_buttons");
    editorCell.setRole(handler.getElementRole());
    return editorCell;
  }

  private static class buttonsListHandler_gq055b_a1b9b1a0 extends RefNodeListHandler {
    public buttonsListHandler_gq055b_a1b9b1a0(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
    }

    public SNode createNodeToInsert(EditorContext editorContext) {
      SNode listOwner = super.getOwner();
      return NodeFactoryManager.createNode(listOwner, editorContext, super.getElementRole());
    }

    public EditorCell createNodeCell(EditorContext editorContext, SNode elementNode) {
      EditorCell elementCell = super.createNodeCell(editorContext, elementNode);
      this.installElementCellActions(this.getOwner(), elementNode, elementCell, editorContext);
      return elementCell;
    }

    public EditorCell createEmptyCell(EditorContext editorContext) {
      EditorCell emptyCell = null;
      emptyCell = super.createEmptyCell(editorContext);
      this.installElementCellActions(super.getOwner(), null, emptyCell, editorContext);
      return emptyCell;
    }

    public void installElementCellActions(SNode listOwner, SNode elementNode, EditorCell elementCell, EditorContext editorContext) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        if (elementNode != null) {
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode));
          elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultReferenceSubstituteInfo) {
          elementCell.setSubstituteInfo(new DefaultChildSubstituteInfo(listOwner, elementNode, super.getLinkDeclaration(), editorContext));
        }
      }
    }
  }

  private EditorCell createConstant_gq055b_c9b1a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_gq055b_c9b1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, true);
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static boolean renderingCondition_gq055b_a2j1b0a(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }

  private EditorCell createConstant_gq055b_c0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_gq055b_c0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, true);
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static boolean renderingCondition_gq055b_a2a0(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
}
