/*
* generated by Xtext
*/
package ru.spbau.luchikhin;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GraphUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ru.spbau.luchikhin.ui.internal.GraphActivator.getInstance().getInjector("ru.spbau.luchikhin.Graph");
	}
	
}
