package Schedule.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 2:
        return new Schedule_BehaviorDescriptor();
      case 1:
        return new Lecture_BehaviorDescriptor();
      case 4:
        return new TimeRange_BehaviorDescriptor();
      case 3:
        return new Time_BehaviorDescriptor();
      case 0:
        return new DaySchedule_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"Schedule.structure.DaySchedule", "Schedule.structure.Lecture", "Schedule.structure.Schedule", "Schedule.structure.Time", "Schedule.structure.TimeRange"};
}
