package Schedule.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DaySchedule_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DaySchedule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Schedule.structure.DaySchedule";
  }
}
