package Schedule.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TimeRange_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TimeRange_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Schedule.structure.TimeRange";
  }
}
