package Tracer.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new CallingTracer_BehaviorDescriptor();
      case 1:
        return new Log_BehaviorDescriptor();
      case 2:
        return new LogFormat_BehaviorDescriptor();
      case 3:
        return new ModificationsTracer_BehaviorDescriptor();
      case 4:
        return new ReferencesTracer_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"Tracer.structure.CallingTracer", "Tracer.structure.Log", "Tracer.structure.LogFormat", "Tracer.structure.ModificationsTracer", "Tracer.structure.ReferencesTracer"};
}
