package Schedule.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_568337036394331826(final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "day", null);
  }

  public static Object propertyMacro_GetPropertyValue_568337036394444179(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "timeRange", true), "begin", true), "hours")) + ":" + Integer.toString(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "timeRange", true), "begin", true), "minutes"));
  }

  public static Object propertyMacro_GetPropertyValue_568337036394526155(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "timeRange", true), "end", true), "hours")) + ":" + Integer.toString(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "timeRange", true), "end", true), "minutes"));
  }

  public static Object propertyMacro_GetPropertyValue_568337036394541935(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), "room"));
  }

  public static Object propertyMacro_GetPropertyValue_568337036394573195(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "presenter");
  }

  public static Object propertyMacro_GetPropertyValue_568337036394433139(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Iterable<SNode> sourceNodesQuery_568337036394327474(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "daySchedules", true);
  }

  public static Iterable<SNode> sourceNodesQuery_568337036394405210(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "lectures", true);
  }
}
