package tracer.behavior;

/*Generated by MPS */


public class ModificationsTracer_BehaviorDescriptor extends Tracer_BehaviorDescriptor {
  public ModificationsTracer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "tracer.structure.ModificationsTracer";
  }
}
