package Stopwatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum TimeUnitType {
  seconds("seconds", "s"),
  milliseconds("milliseconds", "ms"),
  minutes("minutes", "m"),
  hours("hours", "h");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<TimeUnitType> getConstants() {
    List<TimeUnitType> list = ListSequence.fromList(new LinkedList<TimeUnitType>());
    ListSequence.fromList(list).addElement(TimeUnitType.seconds);
    ListSequence.fromList(list).addElement(TimeUnitType.milliseconds);
    ListSequence.fromList(list).addElement(TimeUnitType.minutes);
    ListSequence.fromList(list).addElement(TimeUnitType.hours);
    return list;
  }

  public static TimeUnitType getDefault() {
    return TimeUnitType.seconds;
  }

  public static TimeUnitType parseValue(String value) {
    if (value == null) {
      return TimeUnitType.getDefault();
    }
    if (value.equals(TimeUnitType.seconds.getValueAsString())) {
      return TimeUnitType.seconds;
    }
    if (value.equals(TimeUnitType.milliseconds.getValueAsString())) {
      return TimeUnitType.milliseconds;
    }
    if (value.equals(TimeUnitType.minutes.getValueAsString())) {
      return TimeUnitType.minutes;
    }
    if (value.equals(TimeUnitType.hours.getValueAsString())) {
      return TimeUnitType.hours;
    }
    return TimeUnitType.getDefault();
  }

  private String myValue;

  TimeUnitType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
