package Schedule.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Day {
  Sunday("Sunday", "Sunday"),
  Monday("Monday", "Monday"),
  Tuesday("Tuesday", "Tuesday"),
  Wednesday("Wednesday", "Wednesday"),
  Thursday("Thursday", "Thursday"),
  Friday("Friday", "Friday"),
  Saturday("Saturday", "Saturday");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Day> getConstants() {
    List<Day> list = ListSequence.fromList(new LinkedList<Day>());
    ListSequence.fromList(list).addElement(Day.Sunday);
    ListSequence.fromList(list).addElement(Day.Monday);
    ListSequence.fromList(list).addElement(Day.Tuesday);
    ListSequence.fromList(list).addElement(Day.Wednesday);
    ListSequence.fromList(list).addElement(Day.Thursday);
    ListSequence.fromList(list).addElement(Day.Friday);
    ListSequence.fromList(list).addElement(Day.Saturday);
    return list;
  }

  public static Day getDefault() {
    return null;
  }

  public static Day parseValue(String value) {
    if (value == null) {
      return Day.getDefault();
    }
    if (value.equals(Day.Sunday.getValueAsString())) {
      return Day.Sunday;
    }
    if (value.equals(Day.Monday.getValueAsString())) {
      return Day.Monday;
    }
    if (value.equals(Day.Tuesday.getValueAsString())) {
      return Day.Tuesday;
    }
    if (value.equals(Day.Wednesday.getValueAsString())) {
      return Day.Wednesday;
    }
    if (value.equals(Day.Thursday.getValueAsString())) {
      return Day.Thursday;
    }
    if (value.equals(Day.Friday.getValueAsString())) {
      return Day.Friday;
    }
    if (value.equals(Day.Saturday.getValueAsString())) {
      return Day.Saturday;
    }
    return Day.getDefault();
  }

  private String myValue;

  Day(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
