/**
 * generated by Xtext
 */
package ru.spbau.luchikhin.ui.contentassist;

import ru.spbau.luchikhin.ui.contentassist.AbstractGraphProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class GraphProposalProvider extends AbstractGraphProposalProvider {
}
