package tracer.behavior;

/*Generated by MPS */


public class CallingTracer_BehaviorDescriptor extends Tracer_BehaviorDescriptor {
  public CallingTracer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "tracer.structure.CallingTracer";
  }
}
