package tracer.behavior;

/*Generated by MPS */


public class ReferencesTracer_BehaviorDescriptor extends Tracer_BehaviorDescriptor {
  public ReferencesTracer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "tracer.structure.ReferencesTracer";
  }
}
