package tracer.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Tracer_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Tracer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "tracer.structure.Tracer";
  }
}
