/*
* generated by Xtext
*/
package ru.spbau.luchikhin.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ru.spbau.luchikhin.services.GraphGrammarAccess;

public class GraphParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GraphGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ru.spbau.luchikhin.parser.antlr.internal.InternalGraphParser createParser(XtextTokenStream stream) {
		return new ru.spbau.luchikhin.parser.antlr.internal.InternalGraphParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GraphGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GraphGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
