/*
 * generated by Xtext
 */
package ru.spbau.luchikhin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GraphRuntimeModule extends ru.spbau.luchikhin.AbstractGraphRuntimeModule {

}
