/*
* generated by Xtext
*/
package ru.spbau.luchikhin;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GraphStandaloneSetup extends GraphStandaloneSetupGenerated{

	public static void doSetup() {
		new GraphStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

