/*
* generated by Xtext
*/
package ru.spbau.luchikhin.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import ru.spbau.luchikhin.services.GraphGrammarAccess;

public class GraphParser extends AbstractContentAssistParser {
	
	@Inject
	private GraphGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected ru.spbau.luchikhin.ui.contentassist.antlr.internal.InternalGraphParser createParser() {
		ru.spbau.luchikhin.ui.contentassist.antlr.internal.InternalGraphParser result = new ru.spbau.luchikhin.ui.contentassist.antlr.internal.InternalGraphParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getNodeAccess().getConnectionsAlternatives_2_0(), "rule__Node__ConnectionsAlternatives_2_0");
					put(grammarAccess.getNodeAccess().getGroup(), "rule__Node__Group__0");
					put(grammarAccess.getConnectionAccess().getGroup(), "rule__Connection__Group__0");
					put(grammarAccess.getConnectionAccess().getGroup_2(), "rule__Connection__Group_2__0");
					put(grammarAccess.getModelAccess().getNodesAssignment(), "rule__Model__NodesAssignment");
					put(grammarAccess.getNodeAccess().getNameAssignment_1(), "rule__Node__NameAssignment_1");
					put(grammarAccess.getNodeAccess().getConnectionsAssignment_2(), "rule__Node__ConnectionsAssignment_2");
					put(grammarAccess.getConnectionAccess().getConnectionAssignment_1(), "rule__Connection__ConnectionAssignment_1");
					put(grammarAccess.getConnectionAccess().getConnectionAssignment_2_1(), "rule__Connection__ConnectionAssignment_2_1");
					put(grammarAccess.getNoConnectionAccess().getConnectionAssignment(), "rule__NoConnection__ConnectionAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			ru.spbau.luchikhin.ui.contentassist.antlr.internal.InternalGraphParser typedParser = (ru.spbau.luchikhin.ui.contentassist.antlr.internal.InternalGraphParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GraphGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GraphGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
