package tracer.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("tracer.structure.CallingTracer").super_("tracer.structure.Tracer").parents("tracer.structure.Tracer").create();
      case 1:
        return new ConceptDescriptorBuilder("tracer.structure.Log").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").children(new String[]{"format", "tracers"}, new boolean[]{false, true}).create();
      case 2:
        return new ConceptDescriptorBuilder("tracer.structure.LogFormat").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").properties("time").create();
      case 3:
        return new ConceptDescriptorBuilder("tracer.structure.ModificationsTracer").super_("tracer.structure.Tracer").parents("tracer.structure.Tracer").create();
      case 4:
        return new ConceptDescriptorBuilder("tracer.structure.ReferencesTracer").super_("tracer.structure.Tracer").parents("tracer.structure.Tracer").create();
      case 5:
        return new ConceptDescriptorBuilder("tracer.structure.Tracer").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").abstract_().create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"tracer.structure.CallingTracer", "tracer.structure.Log", "tracer.structure.LogFormat", "tracer.structure.ModificationsTracer", "tracer.structure.ReferencesTracer", "tracer.structure.Tracer"};
}
